# Generated by Django 4.2.1 on 2023-05-20 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id_Especialidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Especialidad Médica',
                'verbose_name_plural': 'Especialidades',
                'db_table': 'especialidad',
            },
        ),
        migrations.CreateModel(
            name='HorarioDeAtencion',
            fields=[
                ('id_Horario', models.AutoField(primary_key=True, serialize=False)),
                ('n_dia_uk', models.IntegerField(unique=True, verbose_name='Número de dia de la setmana a UK (0=diumenge)')),
                ('n_dia_ca', models.IntegerField(unique=True, verbose_name='Número de dia de la setmana aquí (0=dilluns)')),
                ('dia_2_lletres', models.CharField(max_length=6, unique=True, verbose_name='Dia')),
                ('dia_de_la_setmana', models.CharField(max_length=45, unique=True, verbose_name='Dia de la setmana')),
                ('hora_inici', models.DateTimeField()),
                ('hora_fi', models.DateTimeField()),
            ],
            options={
                'verbose_name': ' horarios semanales por cada especialista',
                'verbose_name_plural': 'HorariosDeAtención',
                'db_table': 'HorarioDeAtencion',
            },
        ),
        migrations.RemoveField(
            model_name='especialista',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='especialista',
            name='horariosDeAtencion',
        ),
        migrations.RemoveField(
            model_name='especialista',
            name='id_Turnos',
        ),
        migrations.RemoveField(
            model_name='turnosporespecialista',
            name='horarioDeTurno',
        ),
        migrations.AddField(
            model_name='especialista',
            name='id_Especialidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.especialidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turnosporespecialista',
            name='id_Horario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.horariodeatencion'),
            preserve_default=False,
        ),
    ]
