# Generated by Django 4.2.1 on 2023-05-20 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_especialidad_horariodeatencion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariodeatencion',
            name='id_Especialidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.especialista'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horariodeatencion',
            name='nom_franja',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
