# Generated by Django 4.2.1 on 2023-05-20 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_horariodeatencion_id_especialidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horariodeatencion',
            old_name='id_Especialidad',
            new_name='id_Especialista',
        ),
    ]
