# Generated by Django 4.2.1 on 2023-05-22 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horariodeatencion',
            name='dia_2_lletres',
        ),
        migrations.RemoveField(
            model_name='horariodeatencion',
            name='n_dia_ca',
        ),
        migrations.RemoveField(
            model_name='horariodeatencion',
            name='n_dia_uk',
        ),
        migrations.RemoveField(
            model_name='horariodeatencion',
            name='nom_franja',
        ),
    ]
