# Generated by Django 4.2.1 on 2023-05-31 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_horariodeatencion_dia_2_lletres_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horariodeatencion',
            name='dia_de_la_setmana',
        ),
        migrations.AddField(
            model_name='horariodeatencion',
            name='dia_de_la_semana',
            field=models.CharField(default=1, max_length=45, verbose_name='Dia de la semana'),
            preserve_default=False,
        ),
    ]
