# Generated by Django 4.2.1 on 2023-06-04 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_reservadeturno_pago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especialidad',
            options={'verbose_name': 'EspecialidadMédica', 'verbose_name_plural': 'Especialidades'},
        ),
        migrations.AlterModelOptions(
            name='especialista',
            options={'verbose_name': 'EspecialistaMédico', 'verbose_name_plural': 'Especialistas'},
        ),
        migrations.AlterModelOptions(
            name='horariodeatencion',
            options={'verbose_name': ' horariosSemanalesPorCadaEspecialista', 'verbose_name_plural': 'HorariosDeAtención'},
        ),
        migrations.AlterModelOptions(
            name='turnosporespecialista',
            options={'verbose_name': ' turnosParaEspecialistaMédico', 'verbose_name_plural': 'turnosPorEspecialistas'},
        ),
    ]
