-- MySQL Script generated by MySQL Workbench
-- Sun May  7 12:02:44 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema turnero
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `turnero` ;

-- -----------------------------------------------------
-- Schema turnero
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `turnero` DEFAULT CHARACTER SET utf8mb3 ;
USE `turnero` ;

-- -----------------------------------------------------
-- Table `turnero`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turnero`.`administrador` (
  `id_Administrador` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `DNI` INT NOT NULL,
  `Cargo` VARCHAR(45) NOT NULL,
  `Telefono` INT NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Administrador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `turnero`.`especialista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turnero`.`especialista` (
  `idEspecialista` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `dni` VARCHAR(45) NOT NULL,
  `nroMatricula` VARCHAR(45) NOT NULL,
  `especialidad` VARCHAR(45) NOT NULL,
  `telefono` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `horarioAtencion` TIME NOT NULL,
  `Administrador_id_Administrador` INT NOT NULL,
  PRIMARY KEY (`idEspecialista`),
  INDEX `fk_Especialista_Administrador_idx` (`Administrador_id_Administrador` ASC) VISIBLE,
  CONSTRAINT `fk_Especialista_Administrador`
    FOREIGN KEY (`Administrador_id_Administrador`)
    REFERENCES `turnero`.`administrador` (`id_Administrador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `turnero`.`horarioespecialista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turnero`.`horarioespecialista` (
  `id_horarioEspecialista` INT NOT NULL AUTO_INCREMENT,
  `diaSemana` VARCHAR(45) NOT NULL,
  `horarInicio` TIME NOT NULL,
  `horaFin` TIME NOT NULL,
  `Especialista_idEspecialista` INT NOT NULL,
  PRIMARY KEY (`id_horarioEspecialista`),
  INDEX `fk_horarioEspecialista_Especialista1_idx` (`Especialista_idEspecialista` ASC) VISIBLE,
  CONSTRAINT `fk_horarioEspecialista_Especialista1`
    FOREIGN KEY (`Especialista_idEspecialista`)
    REFERENCES `turnero`.`especialista` (`idEspecialista`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `turnero`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turnero`.`paciente` (
  `idPaciente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `DNI` INT NOT NULL,
  `nroAfiliado` INT NOT NULL,
  `telefono` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `Administrador_id_Administrador` INT NOT NULL,
  PRIMARY KEY (`idPaciente`),
  INDEX `fk_Paciente_Administrador1_idx` (`Administrador_id_Administrador` ASC) VISIBLE,
  CONSTRAINT `fk_Paciente_Administrador1`
    FOREIGN KEY (`Administrador_id_Administrador`)
    REFERENCES `turnero`.`administrador` (`id_Administrador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `turnero`.`obrasocial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turnero`.`obrasocial` (
  `id_ObraSocial` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `plan` VARCHAR(45) NOT NULL,
  `nroAfiliados` INT NOT NULL,
  `Paciente_idPaciente` INT NOT NULL,
  PRIMARY KEY (`id_ObraSocial`, `Paciente_idPaciente`),
  INDEX `fk_ObraSocial_Paciente1_idx` (`Paciente_idPaciente` ASC) VISIBLE,
  CONSTRAINT `fk_ObraSocial_Paciente1`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `turnero`.`paciente` (`idPaciente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `turnero`.`pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turnero`.`pago` (
  `idpago` INT NOT NULL,
  `fecha y hora` DATE NOT NULL,
  `monto` FLOAT NOT NULL,
  PRIMARY KEY (`idpago`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `turnero`.`turnoespecialista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turnero`.`turnoespecialista` (
  `id_turnoEspecialista` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NOT NULL,
  `Hora` TIME NOT NULL,
  `horaHasta` TIME NOT NULL,
  `Especialista_idEspecialista` INT NOT NULL,
  PRIMARY KEY (`id_turnoEspecialista`),
  INDEX `fk_turnoEspecialista_Especialista1_idx` (`Especialista_idEspecialista` ASC) VISIBLE,
  CONSTRAINT `fk_turnoEspecialista_Especialista1`
    FOREIGN KEY (`Especialista_idEspecialista`)
    REFERENCES `turnero`.`especialista` (`idEspecialista`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `turnero`.`reservaturno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turnero`.`reservaturno` (
  `id_reservaTurno` INT NOT NULL AUTO_INCREMENT,
  `paciente` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `Paciente_idPaciente` INT NOT NULL,
  `turnoEspecialista_id_turnoEspecialista` INT NOT NULL,
  `pago_idpago` INT NOT NULL,
  PRIMARY KEY (`id_reservaTurno`),
  INDEX `fk_reservaTurno_Paciente1_idx` (`Paciente_idPaciente` ASC) VISIBLE,
  INDEX `fk_reservaTurno_turnoEspecialista1_idx` (`turnoEspecialista_id_turnoEspecialista` ASC) VISIBLE,
  INDEX `fk_reservaturno_pago1_idx` (`pago_idpago` ASC) VISIBLE,
  CONSTRAINT `fk_reservaTurno_Paciente1`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `turnero`.`paciente` (`idPaciente`),
  CONSTRAINT `fk_reservaTurno_turnoEspecialista1`
    FOREIGN KEY (`turnoEspecialista_id_turnoEspecialista`)
    REFERENCES `turnero`.`turnoespecialista` (`id_turnoEspecialista`),
  CONSTRAINT `fk_reservaturno_pago1`
    FOREIGN KEY (`pago_idpago`)
    REFERENCES `turnero`.`pago` (`idpago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
